name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.12'

jobs:
  lint-security:
    name: Lint & Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black bandit
          
      - name: Run Black format check
        run: black --check --diff src/ tests/
        
      - name: Run Flake8 linting
        run: flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503
        
      - name: Run Bandit security check
        run: bandit -r src/ -ll

  # TODO: Implement remaining CI jobs in ALC-EP006-M02 through ALC-EP006-M06
  # - unit-tests
  # - api-tests  
  # - extended-tests
  # - allure-reporting
  # - docs-deploy
